
var headerText = "Longship Bingo";

var footerText = "<a href='https://forms.gle/kRzYoGoH67Hz3BPL8' target='_blank'>Suggest Tiles</a> - <a href='https://github.com/LongshipStudios/bingo/' target='_blank'>Code available on github</a>";

var winText = "Winner";

var clickSnd = new Audio("audio/click.mp3");

var winSnd = new Audio("audio/win.mp3");

var JSONBingo = {"squares": [
        {"square": "Are we the badies?"},
        {"square": "My Shoe"},
        {"square": "BRB - Being rather British"},
        {"square": "WHAT HO FRIENDO!"},
        {"square": "&lt;DELETED LINK&gt;"},
        {"square": "will.exe has stopped"},
        {"square": "Does anybody need a backpack?"},
        {"square": "Pirate Queen - Little Bear"},
        {"square": "We're still in Subnautica / We never left SOMA"},
        {"square": "Hero to the people Dan Jones!"},
        //{"square": "How goes the hand?"},
        {"square": "Dramatic Duck"},
        {"square": "Twizzlers, Drangoes and Tea"},
        {"square": "It's a kaleidoscope!"},
        {"square": "Tiny Mechs"},
        //{"square": "PORG KET"},
        {"square": "Mr Viking"},
        {"square": "How about nooooooo"},
        {"square": "BRB need tea logo is still up"},
        {"square": "*some Hellsing Abridged quote*"},
        {"square": "SPLEEN THRONE"},
        {"square": "Moose, no! - Moose yes, Moose always yes!"},
        {"square": "Hotel Scipio"},
        {"square": "Eat the rich!"},    	
        {"square": "*Will is sorry for something*"},    	
        {"square": "*Will makes a weird face*"},    	
        {"square": "Jumping back into chat"},    	
        {"square": "*Will plays Chap Hop*"},    	
        {"square": "CYBER something"},    	
        {"square": "SHARKS!"},    	
        {"square": "WHAT ABOUT QUEST!?"},    	
        {"square": "ALL YOU CAN UPGRAD IS STRANTH!?"},    	
        {"square": "*Will cries*"},
        {"square": "Here Comes The Pain Train"},
        {"square": "*Will does a silly voice*"},
        //{"square": "A Ket appears"},
        {"square": "Fecking seagulls"},
        {"square": "NUMPTIES!"},
        {"square": "Look at this Anjanath"},
        {"square": "Floydo!"},
        {"square": "Wafflemancy"},
        {"square": "*Pun on someones username*"},
        {"square": "#RebootEndoTeam"},
        {"square": "Pirate crew"},
        {"square": "SOBA"},
        {"square": "Teeny tiny thing"},
        {"square": "But that's a nother story"},
        {"square": "Uncle Death believes in you"},
        {"square": "Senpai"},
        {"square": "ECHO"},
        {"square": "Neurotoxin"},
        {"square": "Growler"},
        {"square": "Do a murder"},
        {"square": "MFLAFFAFFLAFF"},
        {"square": "Will accidentally ignores someone in chat"},
        {"square": "IT'S NOT A CULT"},
        {"square": "It's a cult"},
        {"square": "Will tries not to waffle but waffles"},
        {"square": "They ain't gonna be in Rush Hour 2"},
        {"square": "Will forgot to tweet, again"},
        {"square": "The game industry is on fire"},
        {"square": "Will apologizes for being human"},
        {"square": "Will apologizes for taking a tea break"},
    ]
};
